### ISSUE TITLE
A SimpleNFA isn't initialized by states consisting of two symbols, e. g. "s0", "s1" etc.

### ISSUE THREAD

**Issue by vrnch** [whitemech/pythomata#102]
**Describe the bug**
A SimpleNFA isn't initialized by states consisting of two symbols, e. g. "s0", "s1" etc.

**To Reproduce**

1. Create a file .py
2. Run the following code snippet:
```
from pythomata import SimpleNFA
from IPython.display import Image

alphabet = {'0', '1'}
states = {'q0', 'q1', 'q2', 'q3'}
initial_state = 'q0'
accepting_states = {'q3'}
transition_function = {
    'q0' : {
        '0' : 'q0',
        '1' : 'q0',
        '0' : 'q1',
        '1' : 'q2'
    },
    'q1' : {
        '0' : 'q3'
    },
    'q2' : {
        '1' : 'q3'
    }
}
nfa = SimpleNFA(states, alphabet, initial_state, accepting_states, transition_function)

picture = nfa.to_graphviz()
picture.format = 'png'
Image(filename=picture.render("./new_nfa")) 
```

**Expected behavior**
The NFA generated by the previous code and similar to this NFA 
![image](https://user-images.githubusercontent.com/55781166/81705111-54073900-9477-11ea-9265-b3f88af25797.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/55781166/81705638-eb6c8c00-9477-11ea-8ad2-480649654224.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser Chome

**Comment by marcofavorito** [comment]
Hi,

the transition function looks wrong, please use the following:

```python 
{'q0': 
    {'0': {'q0', 'q1'}, 
     '1': {'q0', 'q2'}},
 'q1': 
    {'0': {'q3'}},
 'q2': 
    {'1': {'q3'}}}
```
